name: nes
version: 0.1.0.0
maintainer: bikeboi

dependencies:
  - base
  - bytestring
  - array
  - mtl
  - transformers
  - containers
  - stm

executables:
  nes:
    main: Main.hs
    source-dirs: src
    other-modules:
      - CPU
      - CPU.Internal
      - CPU.OpCode
      - CPU.Decode
      - CPU.Debug
      - Memory
      - Util

tests:
  spec:
    main: "Spec.hs"
    source-dirs:
      - src
      - test
    dependencies:
      - hspec
      - QuickCheck
