name: nes
version: 0.1.0.0
maintainer: bikeboi

dependencies:
  - base

  # Data
  - bytestring
  - vector
  - containers
  - array

  # Abstraction
  - mtl
  - transformers
  - recursion-schemes
  - microlens-platform
  - stm

  # Graphics
  - sdl2
  - linear

executables:
  nes:
    main: Main.hs
    source-dirs: src
    other-modules:
      # CPU
      - CPU
      - CPU.ROM
      - CPU.Debug
      - CPU.Internal
      - CPU.OpCode
      - CPU.AddressMode
      - CPU.Decode
      - CPU.Sandbox

      # PPU
      - PPU.Render
      - PPU.Internal

      # Memory
      - Memory

      - Util

tests:
  spec:
    main: "Spec.hs"
    source-dirs:
      - src
      - test
    dependencies:
      - hspec
      - QuickCheck
